go.mod
test.tf

Kjda/sdk v0.4.2

---

resource_check_group.go

calling correct Read func in resourceCheckGroupUpdate

---

Makefile
checkly/provider.go
checkly/provider_test.go
checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go
checkly/test_util.go
docs/guides/installing-the-provider.md
docs/index.md
docs/resources/check-group.md
docs/resources/check.md
main.go

refactored go code into checkly package, added documentation in /docs => fixes  #10

added terraform documentation, moved code into checkly package

---

.goreleaser.yml

fixing indent

---

GNUmakefile
checkly/error_with_log.go
checkly/provider.go
checkly/resource_alert_channel.go
checkly/resource_alert_channel_test.go
checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go
docs/resources/alert-channel.md
docs/resources/check.md
docs/resources/check_group.md
go.mod
go.sum
test.tf

Alert channel management 

---

checkly/resource_check.go

Fixes the activated field not being respected

fix: cast activated to bool

---

checkly/resource_alert_channel.go
docs/resources/alert-channel.md
go.mod
go.sum
test.tf

* Added alert channel flag settings

added AlertChannel flag settings

---

go.mod
go.sum

Add autoAssignAlerts query param to check and groups POST/PUT

---

checkly/consts.go
checkly/helpers.go
checkly/provider.go
checkly/resource_alert_channel.go
checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_snippet.go
go.mod
go.sum

Refactor to checkly 1

---

.github/workflows/release.yml

upgrade to go1.16

---

go.mod
go.sum

refactoring

---

.github/workflows/test.yml
checkly/resource_alert_channel_test.go
checkly/resource_check_group_test.go

enabling acceptance tests

---

.github/workflows/test.yml

Gh actions badge

---

checkly/resource_check_group.go
docs/resources/check_group.md

Resolves https://github.com/checkly/terraform-provider-checkly/issues/69

Add check group missing properties

---

.github/auto_assign.yml

Resolves #79
Add auto_assign action with assigned reviewers

Add auto_assign action for PR's

---

checkly/provider.go

Add support for setting Account ID (only for User API Keys)
> Resolves #88 
> Depends on https://github.com/checkly/checkly-go-sdk/pull/52

feat: add support for account id

---

docs/resources/maintenance_windows.md
docs/resources/public_dashboards.md

Add documentation for maintenance windows and public dashboards

---

docs/guides/getting-started.md

Add docs of how to setup Checkly account id
> Resolves #95 
@ragog would be great if you can give a try to the provider using the new User Keys 🙂🙏

docs: show how to setup checkly account id

---

docs/guides/getting-started.md
docs/index.md

docs: add account id info

---

checkly/provider.go
checkly/resource_trigger_check.go
checkly/resource_trigger_group.go
docs/resources/trigger_check.md
docs/resources/trigger_group.md
go.mod
go.sum
test.tf

Support for command line triggers

---

checkly/provider.go
go.mod
go.sum

Added `SetChecklySource("TF")` from `checkly-go-sdk`.
Depends on: https://github.com/checkly/checkly-go-sdk/pull/65

feat: add checkly source [sc-00]

---

checkly/resource_check_group.go
checkly/resource_check_group_test.go
docs/resources/check_group.md

refactor: make group locations optional

---

checkly/resource_check.go
checkly/resource_check_test.go
demo/api-checks.tf
demo/browser-checks.tf

Support new check intervals (2, 120, 180, 360)
> Resolves #180

feat: support new check intervals

---

checkly/resource_dashboard.go

🥹 resource_dashboard.go: properly assign private dashboard keys

---

checkly/resource_alert_channel.go
demo/alert-channels.tf
docs/resources/alert_channel.md
go.mod
go.sum

Add new phone call alert channel support

feat: add phone call alert channel support [sc-00]

---

.github/CODEOWNERS

chore: update code owners [sc-00]

---

.github/CODEOWNERS

- I think all code owners should be listed on the same line otherwise the last one takes precedence.

Antoinecoutellier/sc 00/update code owners

---

.gitignore
checkly/error_with_log.go
checkly/provider.go
checkly/resource_heartbeat.go
checkly/resource_heartbeat_test.go
checkly/resource_private_locations.go
checkly/test_util.go
go.mod
go.sum

Antoinecoutellier/sc 16785/add terraform support v2

---

checkly/resource_heartbeat.go
checkly/resource_heartbeat_test.go
docs/resources/heartbeat.md

feat: add minutes to heartbeat resource, update docs [sc-18336]

---

checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go
checkly/resource_heartbeat.go
docs/resources/check.md
docs/resources/check_group.md
docs/resources/heartbeat.md
go.mod
go.sum

Adding `alertSettings.parallelRunFailureThreshold` support

feat: add parallel run threshold props [sc-19200]

---

.github/workflows/release.yml

* Replace --rm-dist with --clean as it is updated in the docs

fix: replace --rm-dist with --clean [sc-0]

---

.goreleaser.yml

Update the goreleaser config according to the changes

fix: update goreleaser yaml file [sc-0]

---

checkly/attribute_trigger_incident.go
docs/resources/check.md
docs/resources/heartbeat.md
docs/resources/heartbeat_monitor.md
docs/resources/tcp_check.md
docs/resources/tcp_monitor.md
docs/resources/url_monitor.md

fix: use correct description for the trigger_incident attribute
