go.mod
go.sum

upgraded to the latest checkly-go-sdk
fixes #31

fixing issue #31: update tags when empty

---

checkly/resource_check.go

fixes #63 .. Unfortunately, we can't require target for some assertions based on comparison type, tf ValidateFunc works only on primitive types and it has no access to other schema fields -> 'comparison', the validation will happen on the backend.

making assertion.target optional

---

.gitignore
GNUmakefile
checkly/resource_check.go
docs/resources/check.md
go.mod
install-0.12.sh
install-0.13.sh
test.tf
versions.tf

Add support for high-frequency checks using `frequency_offset`.
Is not 100% but would like to open it as a draft to start reviewing it and validate functionality.
- `frequency_offset` will only be valid for API Checks and when the value of `frequency` equals 0.
- `frequency_offset` is ignored in other scenarios than above.
- `frequency_offset` should not break existing checks and will not present TF changes unless you set the `frequency` to 0 (in a API Check)
> Resolves https://github.com/checkly/terraform-provider-checkly/issues/68
**Depends on https://github.com/checkly/checkly-go-sdk/pull/27**

Support high frequency API Checks (frequency_offset)

---

checkly/resource_check.go
checkly/resource_check_group.go
docs/resources/alert-channel.md
docs/resources/check.md
docs/resources/check_group.md
docs/resources/snippet.md
go.mod
go.sum
test.tf

- Add support for versioned runtimes
> Resolves #75 
> Depends on https://github.com/checkly/checkly-go-sdk/pull/33

feat: suport versioned runtime in checks/groups (runtime_id)

---

docs/guides/getting-started.md
docs/guides/support-for-terraform-0.12.md
docs/index.md

This PR updates the links to the Api Keys page in the app.checklyhq.com, which moved from `app.checklyhq.com/account/api-keys` to `app.checklyhq.com/settings/user/api-keys`. 
I made a small tweak in the copy to reflect the fact that API keys are now user-based and not account-based anymore.

chore: update links to api keys page [4933]

---

docs/resources/public_dashboards.md

Doc fix.
Fixed the swapped doc strings for custom_url and custom_domain.
Fix the example for `custom_domain` - the examples included the scheme (which is not correct) and did not match the example in the doc string.

Fixed docs for custom_url and custom_domain

---

checkly/resource_trigger_check.go
checkly/resource_trigger_group.go
docs/resources/trigger_check.md
docs/resources/trigger_group.md
go.mod
go.sum
test.tf

- Clean up check/group triggers resources
- Add `URL` property to triggers
> Depends on https://github.com/checkly/checkly-go-sdk/pull/63

feat: add url property and clean up trigger resources

---

install-0.13.sh

Small install script error check to check for the presence of `jq` before continuing.
**EDIT**:
Idk if its helpful, but figured I'd mention it, you can link with a Github shortcut URL directly to the latest release, like:
```
https://github.com/checkly/terraform-provider-checkly/releases/latest/download/asset-name.zip
```
Maybe you can just interoplate the users architecture into that string in place of `asset-name.zip` (like `https://github.com/checkly/terraform-provider-checkly/releases/latest/download/terraform-provider-checkly_latest_$platform.zip`) and skip a step from checking the API? 
See bottom of: https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases

feat: add 'jq' check

---

checkly/resource_check.go
docs/guides/resource-examples.md
docs/resources/check.md
go.mod
go.sum
test.tf

The create check API endpoint allows a new param : skipSSL.
> Resolves #112 
> Depends on https://github.com/checkly/checkly-go-sdk/pull/68

Antoinecoutellier/sc 6270/add skip ssl validation to api checks

---

checkly/provider.go

Add the `CHECKLY_API_SOURCE` environment variable. 
This is needed mostly to allow Pulumi provider sets its own source.
> Resolves https://github.com/checkly/terraform-provider-checkly/issues/119

feat: add CHECKLY_API_SOURCE env variable

---

checkly/resource_check.go
docs/guides/getting-started.md
docs/resources/check.md

Flag `sslCertificates` as depreacted
> Resolves #136

chore: flag sslCertificates as deprecated

---

checkly/resource_maintenance_window.go
demo/maintenance_windows.tf
docs/guides/getting-started.md
docs/resources/maintenance_windows.md
go.mod

- Remove unneeded required from maintenance window resource.
- Add better maintenance window examples
- Update docs
> Depends on GO SDK Release 
> Resolves #140

refactor: remove extra `required` fields in maintenance window resource

---

.gitignore
checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go
demo/api-checks.tf
demo/browser-checks.tf
demo/groups.tf
docs/resources/check.md
docs/resources/check_group.md
docs/resources/maintenance_windows.md
examples/provider/provider.tf
examples/resources/checkly_check/resource.tf
examples/resources/checkly_check_group/resource.tf

- Deprecate `ssl_certificates` from groups 
- Update tests and fixtures
> Resolves #116

Deprecate `ssl_certificates` from Groups

---

checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go

- Avoid setting/getting `ssl_certificates` property
- Remove it from docs and fixtures
> Resolves #193

fix: avoid setting ssl_certificate and remove it from tests

---

checkly/resource_check.go
checkly/resource_check_group.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go

Dynamically check for escalation type whenever parsing resource to check (or check to resource)
> Resolves #194

fix: always check for the correct escalation settings when parsing

---

checkly/resource_check.go
checkly/resource_check_group.go

Add default escalation settings when the configuration is missing

fix: add default escalation settings when empty

---

checkly/resource_private_locations.go
checkly/resource_private_locations_test.go
demo/private_locations.tf
docs/resources/private_location.md
examples/resources/checkly_private_location/resource.tf

Otherwise, the private location never reconciles when the icon input isn't used.

fix: ensure private location icon has a default value

---

checkly/resource_dashboard.go
docs/resources/dashboard.md
go.mod
go.sum

Add isPrivate and Keys property to Dashboard resource, this allows user to receive the password when creating a private dashboard using the provider. This uses the same behavior as create Private Location.
Testing steps:
1) On /demo/dashboard.tf add is_private as true
2) Run terraform plan / terraform apply
3) You will see the key on your terraform state

feat: support private dashboard creation

---

GNUmakefile
checkly/resource_check.go
demo/browser-checks.tf
demo/versions.tf
docs/resources/check.md
go.mod
go.sum

Following what was asked in this [thread](https://checklyhq.slack.com/archives/C024ZAJ938S/p1690276802718249) and this [issue](https://github.com/checkly/terraform-provider-checkly/issues/263), this PRs adds the `SSLCheckDomain` property into the `check` resource.
This PRs makes `make dev` command OS agnostic (for `darwin` and `linux`). This affects only the local development environment.
> Depends on https://github.com/checkly/checkly-go-sdk/pull/112
> Depends on https://github.com/checkly/checkly-backend/pull/4579

chore: add ssl_check_domain property [sc-0]

---

CONTRIBUTING.md
checkly/resource_check.go
checkly/resource_check_group.go
docs/resources/check.md
docs/resources/check_group.md
examples/resources/checkly_check/resource.tf
go.mod
go.sum

This PR adds support for retry strategies to checks and check groups. This PR depends on a new release of the checkly-go-sdk with https://github.com/checkly/checkly-go-sdk/pull/113 (that's causing CI to fail currently).

feat: add support for retry strategies

---

checkly/resource_check.go
checkly/resource_check_group.go
docs/resources/check.md
docs/resources/check_group.md

This PR updates the documentation to mark the `double_check` property as deprecated. It also adds additional documentation for `retry_strategy`.

chore(docs): mark double_check as deprecated

---

checkly/resource_check.go
checkly/resource_check_group.go
docs/resources/check.md
docs/resources/check_group.md
examples/resources/checkly_check/resource.tf
go.mod
go.sum

We recently added support for retry strategies in https://github.com/checkly/terraform-provider-checkly/pull/271. This PR updates the `max_attempts` field to the more accurate name `max_retries`.

feat: rename retry strategy max_attempts to max_retries

---

docs/index.md
docs/resources/check.md
docs/resources/check_group.md
examples/provider/provider.tf
examples/resources/checkly_check/resource.tf
examples/resources/checkly_check_group/resource.tf

This PR adds some fixes in the examples that slipped through earlier.
* `double_check` has been deprecated so we should remove it from the examples
* The examples reference Checkly provider version 1.6.10. We actually ended up bumping the minor version, though, so it should be 1.7.1.

docs: remove double_check and use correct provider version

---

checkly/resource_check.go
checkly/resource_check_test.go
docs/resources/check.md
go.mod
go.sum

- Add support for MULTI_STEP checks.
This PR needs https://github.com/checkly/checkly-go-sdk/pull/117 to be merged first.

Antoinecoutellier/sc 17816/add multistep checks to terraform

---

checkly/resource_check.go
checkly/resource_check_group.go
docs/resources/check.md
docs/resources/check_group.md
go.mod
go.sum

Add `runParallel` to check and group constructs to allow simultaneous check run scheduling on multi-locations.
If set to false, the check run will be scheduled in the different locations in a round-robin fashion.

feat(parallel): add `runParallel` to TF check and group constructs [sc-18211]

---

checkly/resource_check.go
docs/resources/check.md

- Add a better explanation in case the alert subscription array is empty or not set.

chore: add description for alert channel subscriptions

---

checkly/resource_check.go
checkly/resource_check_test.go

Resolves https://github.com/checkly/terraform-provider-checkly/issues/287
The Checkly TF Provider currently has validation to check that multi-step checks only use supported runtimes. This validation has a null-pointer-exception, though, since the `runtime_id` is an optional setting. To fix the error, this PR only validates the runtime ID if one is set. 
Before, the validation was only performed when creating a resource. This PR also performs the validation for updating a resource, since someone might change the runtime ID.
Currently the validation just checks that runtime ID set for the check, and ignores any that might be set on a group. Since a runtime ID set at the check level overrides any runtime ID set at the group level, this should work fine for the edge case where one runtime ID …

fix: improve multi-step runtime validation [sc-19433]

---

.github/workflows/terraform-format-and-style.yml
docs/index.md
docs/resources/alert_channel.md
docs/resources/check.md
docs/resources/check_group.md
docs/resources/environment_variable.md
docs/resources/heartbeat.md
docs/resources/private_location.md
docs/resources/snippet.md
examples/provider/provider.tf
examples/resources/checkly_alert_channel/resource.tf
examples/resources/checkly_check/resource.tf
examples/resources/checkly_check_group/resource.tf
examples/resources/checkly_environment_variable/resource.tf
examples/resources/checkly_heartbeat/resource.tf
examples/resources/checkly_private_location/resource.tf
examples/resources/checkly_snippet/resource.tf

Currently, examples are not formatted with `terraform fmt`, which makes further tooling changes annoying.
This PR applies proper formatting to examples, and adds a new GitHub workflow that comments on PRs that change Terraform files with the result of `terraform fmt` and reports a failing check. I have tested the workflow by pushing commits with incorrect formatting (and then removing those commits again which is why they cannot be seen).

chore: apply terraform fmt to all examples

---

go.mod
go.sum

Previously, applying these values with non-empty lists and then attempting to apply them again with empty lists would keep the previously applied non-empty list due to a JSON serialization oversight in the Go SDK and API oddities.

fix: allow `locations` and `private_locations` to be set to empty lists [sc-23129]

---

checkly/resource_tcp_check.go
checkly/resource_tcp_check_test.go
docs/resources/tcp_check.md

The maximum values were reduced at the backend level and the defaults were changed as well. This change syncs both values to current values used by the backend.
This change is technically backwards incompatible, but even the current version is broken right now if the user relies on default values.

fix: use updated limits for TCP check degraded/max response time [sc-23431]

---

checkly/resource_client_certificate.go

This change makes it so that a `checkly_client_certificate`'s `private_key` is no longer updated based on the backend response. The backend no longer returns a value for this field.

fix: always keep original client certificate key, backend no longer returns it [sc-23507]

---

.github/workflows/test.yml

fix(ci): avoid flaky tests due to conflicting resources by limiting concurrency [sc-23866]

---

checkly/resource_dashboard.go
checkly/resource_dashboard_test.go
docs/resources/dashboard.md
go.mod
go.sum

This PR adds support for the following new attributes in the `checkly_dashboard` resource:
- `show_header`
- `enable_incidents`
- `expand_checks`
- `show_check_run_links`
- `custom_css`
- `show_p95`
- `show_p99`
The default values for each are the same as the backend default values, meaning there's no change to previous behavior.
Additionally, the `header` attribute is now required, because the backend requires it. Because it was effectively already required, this is not a breaking change.
Extensive tests were created with Claude.
Closes #248.

feat: add support for enable_incidents and other dashboard properties [sc-25022]

---

checkly/attribute_retry_strategy.go
checkly/resource_check_group_test.go
checkly/resource_check_test.go
checkly/resource_tcp_monitor_test.go
checkly/resource_url_monitor_test.go
docs/resources/check.md
docs/resources/check_group.md
docs/resources/tcp_check.md
docs/resources/tcp_monitor.md
docs/resources/url_monitor.md

This PR adds a new `only_on` attribute to retry strategies, which can currently be used to limit retries to network errors.
Example usage:
```
retry_strategy {
type = "SINGLE_RETRY"
only_on {
network_error = true
}
}
```

feat: retry strategies can now be limited to network errors only [SIM-104]
